// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqaykpnmpqkvozdrrceq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYXlrcG5tcHFrdm96ZHJyY2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTcyODIsImV4cCI6MjA2ODA5MzI4Mn0.4Ju7kL4ucfVCHqa_Kqf6p4AUZ8hdgYNzRnX-5KvwKn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});